# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "my-awesome-app"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass

app:
  token:
    secret: m#MySesecret2021
    issuer: BackendService
  email:
    from: phetchpirat@gmail.com

