# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
